---
name: Publish to github pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

defaults:
  run:
    working-directory: packages/demo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14'

      - run: yarn install
      - run: yarn run dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/demo/dist
